---
- name: "Generate config file for containerd"
  ansible.builtin.shell:
    cmd: "containerd config default > /etc/containerd/config.toml"
  listen: "containerd"

- name: "Config SystemdCgroup at containerd"
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: '(\s*)SystemdCgroup'
    line: '\1SystemdCgroup = true'
    backrefs: true
  listen: "containerd"

- name: "Restart containerd.service"
  ansible.builtin.systemd:
    name: "containerd.service"
    enabled: true
    daemon_reload: true
    state: restarted
  listen: "containerd"
