---
- name: "Add docker repo"
  block:
    - name: "Add docker public signing key"
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: "{{ docker_gpg_key }}"
        mode: 0644
    - name: "Add Docker apt repository"
      ansible.builtin.apt_repository:
        repo: "deb [signed-by={{ docker_gpg_key }}] https://download.docker.com/linux/ubuntu/ {{ ansible_distribution_release }} stable"
        state: present
        filename: docker.list

- name: "Install containerd"
  ansible.builtin.apt:
    name: containerd.io
    state: present
    update_cache: true
  notify: "containerd"

