---
- name: "Create kubernetes cluster"
  become: true
  become_method: sudo
  debugger: never
  hosts: all
  tasks:
    - name: "Prepare system"
      ansible.builtin.import_role:
        name: init

    - name: "Install container runtime"
      ansible.builtin.import_role:
        name: cri

    - name: "Install kubernetes"
      ansible.builtin.import_role:
        name: kubernetes

- name: "Set up kubernetes cluster"
  become: true
  gather_facts: false
  hosts: control_plane
  tasks:
    - name: "Initialize the cluster"
      ansible.builtin.import_role:
        name: cp
  tags: cp
