---
- name: "Create kubernetes cluster"
  become: true
  debugger: never
  hosts: all
  tasks:
    - name: "Prepare system"
      ansible.builtin.import_role:
        name: init

    - name: "Install container runtime"
      ansible.builtin.import_role:
        name: cri

    - name: "Install kubernetes"
      ansible.builtin.import_role:
        name: kubernetes

- name: "Set up kubernetes cluster"
  become: true
  gather_facts: false
  hosts: control_plane
  tasks:
    - name: "Initialize the cluster"
      ansible.builtin.import_role:
        name: cp
  tags: cp

- name: "Get command to joins the cluster"
  become: true
  hosts: control_plane
  gather_facts: false
  tags: worker
  tasks:
    - name: "Get join cmd"
      ansible.builtin.shell:
        cmd: kubeadm token create --print-join-command
      register: join_cmd

- name: "Worker join to cluster"
  become: true
  hosts: worker
  gather_facts: false
  tags: worker
  tasks:
    # - name: "Reset worker"
    #   ansible.builtin.shell:
    #     cmd: kubeadm reset -f

    - name: "Join cluster"
      ansible.builtin.shell:
        cmd: "{{ hostvars[groups['control_plane'][0]].join_cmd.stdout_lines[0] }}"
        creates: /etc/kubernetes/kubelet.conf
  
